<?php

/**
 * Implements hook_views_api().
 */
function tfa_nudge_views_api() {
  return array(
    'api' => '3.0',
  );
}

/**
 * Implements hook_menu()
 */
function tfa_nudge_menu(){
  $items = array();
  $items['admin/config/people/tfa_nudge'] = array(
    'title' => 'Two-factor Authentication Nudge Settings',
    'description' => 'Manage TFA Nudge Settings',
    'page callback' => 'drupal_get_form',
    'type' => MENU_CALLBACK,
    'page arguments' => array('tfa_nudge_admin_settings_form', 1),
    'access arguments' => array('administer tfa_nudge settings'),
    'file' => 'tfa_nudge.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function tfa_nudge_permission(){
  $perm = array(
    'administer tfa_nudge settings' => array(
      'title' => t('Administer TFA Nudge Settings'),
    )
  );
  return $perm;
}

  );

}

}
function tfa_nudge_reminder_mail($key, &$message){
  $message['subject'] = variable_get('subject', 'Hey you dont have tfa enabled');
  $message['body'] = variable_get('body', 'Enable it');
  dpm($message);
  drupal_mail_system()->mail($message);
}
